---
title: "Practices"
author: "Zidani Test"
date: "1/19/2021"
output: html_document
---

```{r}
x <- factor(c("yes", "yes","no","yes","yes", "no"))
x
table(x)
unclass(x)

```


#NAMING IN R (using the names Attribute)

# naming vectors
```{r}
x <- 1:3
print (x)
names(x) <- c("may","june","july")

print(x)
```
# Naming Lists
```{r}
Y <- list(first=1,second=2,third=3)
Y
```
#Naming Matrices
```{r}
# creating the matrix x
x<- matrix(data = 1:6, nrow = 2,ncol = 3)
x
dimnames(x)<- list(c("A","B"), c("d","e","f"))
x
```


```{r}
# calculating memory Requirements
 #if data frame has 1 500 000 rows and 120 columns given that its a numeric data
= 1500000*120*8bytes/numeric
=144000000
=144000000/2^20 bytes/MB
=1,373.29MB
=1.34GB

```

```{r}
y <- data.frame(a=1,b="a")
# dput is used for restructuring an r object
dput(y)
structure(list(a= 1, 
               b = structure(1L, .Label = "a",class = "factor")),
          .Names = c("a","b"),row.names = c(NA, -1L),
          class = "data.frame")
dput(y,file = "y.R")
new.y<- dget("y.R")

```

```{r}
new.y
```

```{r}
# dump is for soring multiple r objects
X <- "fooo"
Y <- data.frame(a=1,b = "a")
dump(c("X","Y"), file = "data.R")
#rm(X,Y)
#source("data.R")

```

subsetting in R
```{r}
x<-c("a","b","c","d","e","f","a")

x[1]
x[3]
x[1:4]
x[x > "a"]
u <- x > "a"
u
```
Subsetting Lists
```{r}
x <-list(foo=1:4, bar= 0.6)
x[1]
# second element in  x
x[[2]]

x$bar
x[["bar"]]
x["bar"]
```

#Subsetting a Matrix
```{r}
x<-matrix(1:6,2,3)
print(x)
x[1,2] # row 1 column 2

x[2,1] # row 2 column 1

x[1,] #print  row 1
x[,2] # print column 2
```
# retrieving a matrix as a matrix by using drop = FALSE
```{r}

x<-matrix(1:6,2,3)
x[1,2]# returns a vector

x[1,2, drop = FALSE]# retirns a  matrix with dimensions

```

# retieving a column  and row  returns a vector except specified otherwise
```{r}
x<- matrix(1:6,2,3)
x[1,] #returns a vector

x[1,,drop = FALSE] # returns a matrix


```
#partial matching
```{r}
# partial matching just takes the stress of typing on and on 
x <- list(aardvark = 1:5,bino = 1:3)
x$a #prints all element in aardvark
x$b

x[["a"]]

x[["a",exact = FALSE]]
```

#Removing NA values
```{r}
x <- c(1,2,NA,4,NA,5)
bad <- is.na(x) # checks for null values
bad
x[!bad] # to return values aside null


```

```{r}
x <- c(1,2, NA, 4, NA,5)
y <- c("a","b",NA,"d",NA,"f")
good <- complete.cases(x,y)
good
x[good]
y[good]
```
```{r}
airquality[47,]

```

```{r}
airquality
#View(airquality)
good <- complete.cases(airquality)#remove all rows with NA
View(good)
c <- mean(good$Ozone)
c
airquality[good,][1:6, ]
```

```{r}
airquality
b<-airquality[which(airquality$Month==5),]
b
#c<-mean(b$Temp)
c
```
```{r}
m <-airquality[which(airquality$Ozone > 31 & airquality$Temp >90),]
m
mean(m$Solar.R)
```

```{r}
airquality
we <- na.omit(airquality$Ozone)
we
wee<-mean(we)
wee
#bad <-(sum(is.na(airquality$Ozone)))
#bad

```

#vectorized Operations
```{r}
x<- 1:4; y <- 6:9
x+y
x>2
x>=2
y==8
x*y
x/y

```
#vectorized Matrix Operation
```{r}
x<- matrix(1:4,2,2); y<-matrix(rep(10,4),2 ,2) # vector y means reprensent 10 fourtimes
print(y)
print(x)

x*y # element - wise multiplication
x/y

```

```{r}
# to perform a true matrix mulitiplication on  "%%" is required
x%*%y 
```

```{r}
x <- c(4,TRUE)
class(x)
```
```{r}
x <- list(2, "a", "b", TRUE)
class(x)
y<-x[[1]]
y
class(y)
```

```{r}
x <- c(1,3, 5) 
y <- c(3, 2, 10)
cbind(x, y)
```
```{r}
x <- list(2, "a", "b", TRUE)
x[[1]] 
class(x)

```

```{r}
x <- 1:4 
y <- 2:3
b<-x + y
b
class(b)
```

